
export const Film =[
  {
    id:Math.floor(Math.random() * 100000),
    title:"Crazy, Stupid, Love ", 
    description:"A tout juste quarante ans, Cal Weaver mène une vie de rêve - bonne situation, belle maison, enfants formidables et mariage parfait avec sa petite amie du lycée. Mais lorsqu’il apprend que sa femme, Emily, le trompe et demande le divorce, sa vie « parfaite » s’écroule. Pire, dans le monde des célibataires d’aujourd’hui, Cal, qui n’a plus dragué depuis des lustres, se révèle un modèle d’anti séduction. Passant désormais ses soirées à bouder tout seul au bar du coin, l’infortuné Cal est pris en main comme complice et protégé d’un séduisant trentenaire, Jacob Palmer. Pour l’aider à oublier sa femme et à commencer une nouvelle vie, Jacob tente de faire découvrir à Cal les nombreuses perspectives qui s’offrent à lui : femmes en quête d’aventures, soirées arrosées entre copains et un chic supérieur à la moyenne.", 
    posterURL:"https://www.cpasfini.me/uploads/posts/covers/c5f3fef00e757d8a8fdc0007ec56a033.jpg",
    videoURL:"https://www.youtube.com/embed/s0s3hcjtueQ",
    Origine: "U.S.A.",
    Datesortie: "2021",
    Genre: "Comédie",
    duree: "  1h 55min",
    Qualite: "HDLight",
    rating:"5",
  },
    {
      id:Math.floor(Math.random() * 100000),
      title:"Infinite", 
      description:"Un schizophrène découvre l'existence d'une société secrète vieille de plusieurs siècles, la Cognomina. Les membres ont un souvenir précis de leur vie passée et certains ont même contribué à des changements importants dans l'Histoire. Afin d'arrêter les projets d'un cerveau maléfique qui souhaite la destruction de la planète, le groupe doit faire équipe avec l'homme au trouble psychiatrique. Les hallucinations de ce dernier sont en fait des souvenirs d'au moins deux de ses vies passées.", 
      posterURL:"https://www.cpasfini.me/uploads/posts/covers/9a1d9b4da4c111692019e17d52f4e975.jpg",
      videoURL:"https://www.youtube.com/embed/iZWri7iU_n0",
      Origine: "U.S.A.",
      Datesortie: "2021",
      Genre: "Action",
      duree: "1h 46min",
      Qualite: "HDLight",
      rating:"2",


    },
    {
      id:Math.floor(Math.random() * 100000),
      title:"Matrix Resurrections", 
      description:"MATRIX RESURRECTIONS nous replonge dans deux réalités parallèles – celle de notre quotidien et celle du monde qui s’y dissimule. Pour savoir avec certitude si sa réalité propre est une construction physique ou mentale, et pour véritablement se connaître lui-même, M. Anderson devra de nouveau suivre le lapin blanc. Et si Thomas... Neo... a bien appris quelque chose, c’est qu’une telle décision, quoique illusoire, est la seule manière de s’extraire de la Matrice – ou d’y entrer... Bien entendu, Neo sait déjà ce qui lui reste à faire. Ce qu’il ignore en revanche, c’est que la Matrice est plus puissante, plus sécurisée et plus redoutable que jamais. Comme un air de déjà vu...", 
      posterURL:"https://www.cpasfini.me/uploads/posts/covers/ebdfbcc917ee47bea176baf406b4e99b.jpg",
      videoURL:"https://www.youtube.com/embed/Tj63xbpKnqo",
      Origine: "U.S.A.",
      Datesortie: "2021",
      Genre: "Action",
      duree: "2h 28min",
      Qualite: "HDLight",
      rating:"3",
    },
    {
      id:Math.floor(Math.random() * 100000),
      title:"les Éternels", 
      description:"Depuis l’aube de l’humanité, les Éternels, un groupe de héros venus des confins de l’univers, protègent la Terre. Lorsque les Déviants, des créatures monstrueuses que l’on croyait disparues depuis longtemps, réapparaissent mystérieusement, les Éternels sont à nouveau obligés de se réunir pour défendre l’humanité…", 
      posterURL:"https://www.cpasfini.me/uploads/posts/2022-01/1641988313_5wnpjdg.jpg",
      videoURL:"https://www.youtube.com/embed/nHcubNwuKFA",
      Origine: "U.S.A.",
      Datesortie: "2021",
      Genre: "fiction",
      duree: " 2h 37min",
      Qualite: "HDLight",
      rating:"4",
    },
    {
      id:Math.floor(Math.random() * 100000),
      title:"The Private Life ", 
      description:"Depuis l’aube de l’humanité, les Éternels, un groupe de héros venus des confins de l’univers, protègent la Terre. Lorsque les Déviants, des créatures monstrueuses que l’on croyait disparues depuis longtemps, réapparaissent mystérieusement, les Éternels sont à nouveau obligés de se réunir pour défendre l’humanité…", 
      posterURL:"https://www.cpasfini.me/uploads/posts/2022-02/1645125416_19eec0c6521a602e6af1c0b81b64ae9d.jpg",
      videoURL:"https://www.youtube.com/embed/S06abmL_lS0",
      Origine: "U.S.A.",
      Datesortie: "2021",
      Genre: " Drame",
      duree: " 1h 11min",
      Qualite: "HDLight",
      rating:"2",
    },
    
    {
      id:Math.floor(Math.random() * 100000),
      title:"The In Between", 
      description:"Après avoir perdu son grand amour dans un tragique accident, une adolescente au cœur brisé se met à croire qu'il lui envoie des signes d'outre-tombe.", 
      posterURL:"https://www.cpasfini.me/uploads/posts/covers/29880d654d2591e9f1ac091466e600ab.jpg",
      videoURL:"https://www.youtube.com/embed/l5i6U22MaBo",
      Origine: "U.S.A.",
      Datesortie: "2021",
      Genre: " ramance",
      duree: "  1h 55min",
      Qualite: "HDLight",
      rating:"5",
    },
    {
      id:Math.floor(Math.random() * 100000),
      title:"X-Men: Dark Phoenix  ", 
      description:"Dans cet ultime volet, les X-MEN affrontent leur ennemi le plus puissant, Jean Grey, l'une des leurs.Au cours d'une mission de sauvetage dans l'espace, Jean Grey frôle la mort, frappée par une mystérieuse force cosmique. De retour sur Terre, cette force la rend non seulement infiniment plus puissante, mais aussi beaucoup plus instable. En lutte contre elle-même, Jean Grey déchaîne ses pouvoirs, incapable de les comprendre ou de les maîtriser. Devenue incontrôlable et dangereuse pour ses proches, elle défait peu à peu les liens qui unissent les X-Men.", 
      posterURL:"https://www.cpasfini.me/uploads/posts/covers/dffbff82ca822e11e70b508419cb0604.jpg",
      videoURL:"https://www.youtube.com/embed/S06abmL_lS0",
      Origine: "U.S.A.",
      Datesortie: "2021",
      Genre: " Drame",
      duree: " 1h 11min",
      Qualite: "HDLight",
      rating:"3",
    },
    
    {
      id:Math.floor(Math.random() * 100000),
      title:"Maison de Retraite", 
      description:"Afin d’éviter la case prison, Milann, 30 ans, est contraint d’effectuer 300 heures de travaux d’intérêts généraux dans une maison de retraite, Les Mimosas. Ses premières semaines sont un véritable enfer ! Mais il se fait rapidement adopter par les retraités, en particulier par une bande de 7 inséparables qui lui apprennent, chacun à leur manière, leur vision de la vie. Au fil des semaines, Milann découvre que l’établissement profite de la vulnérabilité de ses pensionnaires pour les arnaquer. Il décide alors d’organiser une grande évasion, mais il n’est pas au bout de ses peines...", 
      posterURL:"https://www.cpasfini.me/uploads/posts/covers/dd7bef9f0b5b490492e05c32997adf59.jpg",
      videoURL:"https://www.youtube.com/embed/q8C_c-nlM",
      Origine: "U.S.A.",
      Datesortie: "2019",
      Genre: "  Comédie",
      duree: "  1h 35min",
      Qualite: "HDLight",
      rating:"5",
    },
    ]; 